In [82]:
def vander(x,N,increasing):
    if increasing == True:
        matrix = [[x[i-1]**(j-1) for j in range(1,N+1)] for i in range(1,len(x)+1)]
    elif increasing == False:
        matrix = [[x[i-1]**(j-1) for j in range(1,N+1)][::-1] for i in range(1,len(x)+1)]
    else:
        print("Wrong input! Please execute again")
    return np.array([matrix])
    
print(vander([1,7,3,5],3,False))

[[[ 1  1  1]
  [49  7  1]
  [ 9  3  1]
  [25  5  1]]]


In [98]:
import numpy as np
def find_moving_average(l,w):
    rep = np.repeat(1.0,w)/w
    smas = np.convolve(l,rep,'valid')
    return smas

n = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print("Thus, the moving average sequence has {} values: ".format(len(find_moving_average(n, 3))) + str(find_moving_average(n, 3)))

Thus, the moving average sequence has 11 values: [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
